### get all ideas
GET http://localhost:3000/idea

### create new idea
POST http://localhost:3000/idea HTTP/1.1
Content-Type: application/json

{
    "title": "Learn to bake bread"
}

### get all list items
GET http://localhost:3000/list

### get single list item
GET http://localhost:3000/list/item/639827babb802ed8b8d14b03

### create new list item
POST http://localhost:3000/list HTTP/1.1
Content-Type: application/json

{
    "title": "See the Northern Lights",
    "cost": 50,
    "location": "Alaska",
    "supplies": "Food and blankets",
    "notes": "Yay!"
}

### get single profile
GET http://localhost:3000/profile/639827babb802ed8b8d14b03

### create new profile
POST http://localhost:3000/profile HTTP/1.1
Content-Type: application/json

{
    "email": "courtneylamx@gmail.com"
}

### get all reminders
GET http://localhost:3000/reminder

### get single reminder
GET http://localhost:3000/reminder/639827babb802ed8b8d14b03

### create new reminder
POST http://localhost:3000/reminder HTTP/1.1
Content-Type: application/json

{
    "title": "Go to Paris",
    "date": "October 20",
    "time": "12:00",
    "items": []
}